using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AutoMapper;
using Domain.Contracts;
using Domain.Enums;
using Domain.Models;
using ServiceAbstraction.IJournalPosting;

namespace Service.Services.JournalPosting
{
    /// <summary>
    /// Input model for journal entry line creation.
    /// </summary>
    public class JournalEntryLineInput
    {
        public Account Account { get; set; }
        public decimal? Debit { get; set; }
        public decimal? Credit { get; set; }
        public int? CostCenterId { get; set; }
    }

    public class JournalPostingService : IJournalPostingService
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        // Default account codes
        private const string AccountCodeCash = "1101";
        private const string AccountCodeLCMargin = "1102";
        private const string AccountCodeAccountsReceivable = "1201";
        private const string AccountCodeInventory = "1301";
        private const string AccountCodeWIP = "1302";
        private const string AccountCodeAccountsPayable = "2101";
        private const string AccountCodeSalaryPayable = "2102";
        private const string AccountCodeRevenue = "4101";
        private const string AccountCodeCommissionRevenue = "4201";
        private const string AccountCodeSalaryExpense = "5101";
        private const string AccountCodeShippingExpense = "5102";
        private const string AccountCodeFabricationExpense = "5103";
        private const string AccountCodeCOGS = "5104";

        public JournalPostingService(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork ?? throw new ArgumentNullException(nameof(unitOfWork));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }

        private async Task<Account> GetAccountByCodeAsync(string code, CancellationToken cancellationToken)
        {
            var account = await _unitOfWork.Repository<Account, int>()
                .GetFirstOrDefaultAsync(a => a.Code == code, null, false, cancellationToken);
            return account ?? throw new InvalidOperationException($"Account with code '{code}' not found. Please seed the chart of accounts first.");
        }

        private async Task<decimal> GetExchangeRateAsync(CurrencyType fromCurrency, CurrencyType toCurrency, CancellationToken cancellationToken)
        {
            if (fromCurrency == toCurrency)
                return 1m;

            var rate = await _unitOfWork.Repository<ExchangeRate, int>()
                .GetFirstOrDefaultAsync(
                    r => r.FromCurrency == fromCurrency && r.ToCurrency == toCurrency,
                    null, false, cancellationToken);

            if (rate != null)
                return rate.Rate;

            // Try reverse rate
            var reverseRate = await _unitOfWork.Repository<ExchangeRate, int>()
                .GetFirstOrDefaultAsync(
                    r => r.FromCurrency == toCurrency && r.ToCurrency == fromCurrency,
                    null, false, cancellationToken);

            if (reverseRate != null && reverseRate.Rate != 0)
                return 1m / reverseRate.Rate;

            // Default: assume 1:1 if no rate found (for EGP base)
            return 1m;
        }

        private async Task<JournalEntry> CreateJournalEntryAsync(
            string sourceType, int sourceId,
            CurrencyType currency, string description,
            JournalEntryLineInput[] lines,
            CancellationToken cancellationToken)
        {
            var baseCurrency = CurrencyType.EGP;
            var exchangeRate = await GetExchangeRateAsync(currency, baseCurrency, cancellationToken);

            var entry = new JournalEntry
            {
                ReferenceNumber = $"JE-{sourceType}-{sourceId}-{DateTime.UtcNow:yyyyMMddHHmmss}",
                EntryDate = DateTime.UtcNow,
                Description = description,
                Currency = currency,
                SourceType = sourceType,
                SourceId = sourceId,
                IsAutoGenerated = true
            };

            await _unitOfWork.Repository<JournalEntry, int>().AddAsync(entry, cancellationToken);
            await _unitOfWork.SaveChangesAsync(cancellationToken);

            foreach (var line in lines)
            {
                var debit = line.Debit ?? 0m;
                var credit = line.Credit ?? 0m;

                var entryLine = new JournalEntryLine
                {
                    JournalEntryId = entry.Id,
                    AccountId = line.Account.Id,
                    CostCenterId = line.CostCenterId,
                    Debit = debit,
                    Credit = credit,
                    ExchangeRateToBase = exchangeRate,
                    DebitBaseCurrency = debit * exchangeRate,
                    CreditBaseCurrency = credit * exchangeRate
                };

                await _unitOfWork.Repository<JournalEntryLine, int>().AddAsync(entryLine, cancellationToken);
            }

            await _unitOfWork.SaveChangesAsync(cancellationToken);

            // Reload to verify balance
            var savedEntry = await _unitOfWork.Repository<JournalEntry, int>()
                .GetFirstOrDefaultAsync(e => e.Id == entry.Id, null, false, cancellationToken);

            if (savedEntry != null && !savedEntry.IsBalanced)
            {
                throw new InvalidOperationException(
                    $"JournalEntry #{entry.Id} is not balanced! " +
                    $"TotalDebitBase={savedEntry.TotalDebitBase}, TotalCreditBase={savedEntry.TotalCreditBase}");
            }

            return entry;
        }

        // ─── Invoice Issuance ──────────────────────────────────────────────────
        // Debit:  Accounts Receivable (1201) — Amount owed by client
        // Credit: Revenue (4101) — Invoice total
        public async Task PostInvoiceAsync(Invoice invoice, CancellationToken cancellationToken = default)
        {
            var transaction = await _unitOfWork.BeginTransactionAsync(cancellationToken);
            try
            {
                var arAccount = await GetAccountByCodeAsync(AccountCodeAccountsReceivable, cancellationToken);
                var revenueAccount = await GetAccountByCodeAsync(AccountCodeRevenue, cancellationToken);

                var entry = await CreateJournalEntryAsync(
                    "Invoice", invoice.Id,
                    invoice.Currency,
                    $"Invoice #{invoice.InvoiceNumber} — Client #{invoice.ClientId}",
                    new JournalEntryLineInput[]
                    {
                        new JournalEntryLineInput { Account = arAccount, Debit = invoice.TotalAmount, Credit = null, CostCenterId = invoice.TenderId },
                        new JournalEntryLineInput { Account = revenueAccount, Debit = null, Credit = invoice.TotalAmount, CostCenterId = invoice.TenderId }
                    },
                    cancellationToken);

                invoice.JournalEntryId = entry.Id;
                _unitOfWork.Repository<Invoice, int>().Update(invoice);
                await _unitOfWork.SaveChangesAsync(cancellationToken);

                await transaction.CommitAsync(cancellationToken);
            }
            catch
            {
                await transaction.RollbackAsync(cancellationToken);
                throw;
            }
        }

        // ─── Payment Received ──────────────────────────────────────────────────
        // Debit:  Cash/Bank (1101) — Amount received
        // Credit: Accounts Receivable (1201) — Reduces client's balance
        public async Task PostPaymentAsync(Payment payment, Invoice invoice, CancellationToken cancellationToken = default)
        {
            var transaction = await _unitOfWork.BeginTransactionAsync(cancellationToken);
            try
            {
                var cashAccount = await GetAccountByCodeAsync(AccountCodeCash, cancellationToken);
                var arAccount = await GetAccountByCodeAsync(AccountCodeAccountsReceivable, cancellationToken);

                var entry = await CreateJournalEntryAsync(
                    "Payment", payment.Id,
                    invoice.Currency,
                    $"Payment #{payment.Id} — Invoice #{invoice.InvoiceNumber}",
                    new JournalEntryLineInput[]
                    {
                        new JournalEntryLineInput { Account = cashAccount, Debit = payment.Amount, Credit = null, CostCenterId = invoice.TenderId },
                        new JournalEntryLineInput { Account = arAccount, Debit = null, Credit = payment.Amount, CostCenterId = invoice.TenderId }
                    },
                    cancellationToken);

                payment.JournalEntryId = entry.Id;
                _unitOfWork.Repository<Payment, int>().Update(payment);
                await _unitOfWork.SaveChangesAsync(cancellationToken);

                await transaction.CommitAsync(cancellationToken);
            }
            catch
            {
                await transaction.RollbackAsync(cancellationToken);
                throw;
            }
        }

        // ─── Salary Approved ───────────────────────────────────────────────────
        // Debit:  Salary Expense (5101) — Net salary cost
        // Credit: Salary Payable (2102) — Liability to employee
        public async Task PostSalaryAsync(Salary salary, CancellationToken cancellationToken = default)
        {
            var transaction = await _unitOfWork.BeginTransactionAsync(cancellationToken);
            try
            {
                var expenseAccount = await GetAccountByCodeAsync(AccountCodeSalaryExpense, cancellationToken);
                var payableAccount = await GetAccountByCodeAsync(AccountCodeSalaryPayable, cancellationToken);

                var entry = await CreateJournalEntryAsync(
                    "Salary", salary.Id,
                    CurrencyType.EGP, // Salaries are always in local currency
                    $"Salary #{salary.Id} — Employee #{salary.EmployeeId} — {salary.Month}/{salary.Year}",
                    new JournalEntryLineInput[]
                    {
                        new JournalEntryLineInput { Account = expenseAccount, Debit = salary.NetSalary, Credit = null, CostCenterId = null },
                        new JournalEntryLineInput { Account = payableAccount, Debit = null, Credit = salary.NetSalary, CostCenterId = null }
                    },
                    cancellationToken);

                salary.JournalEntryId = entry.Id;
                _unitOfWork.Repository<Salary, int>().Update(salary);
                await _unitOfWork.SaveChangesAsync(cancellationToken);

                await transaction.CommitAsync(cancellationToken);
            }
            catch
            {
                await transaction.RollbackAsync(cancellationToken);
                throw;
            }
        }

        // ─── PurchaseOrder Issuance ────────────────────────────────────────────
        // Debit:  Inventory (1301) — Cost of goods
        // Credit: Accounts Payable (2101) — Amount owed to Principal
        public async Task PostPurchaseOrderAsync(PurchaseOrder purchaseOrder, CancellationToken cancellationToken = default)
        {
            var transaction = await _unitOfWork.BeginTransactionAsync(cancellationToken);
            try
            {
                var inventoryAccount = await GetAccountByCodeAsync(AccountCodeInventory, cancellationToken);
                var apAccount = await GetAccountByCodeAsync(AccountCodeAccountsPayable, cancellationToken);

                var totalAmount = purchaseOrder.Items?.Sum(i => i.UnitCost * i.Quantity) ?? 0m;

                var entry = await CreateJournalEntryAsync(
                    "PurchaseOrder", purchaseOrder.Id,
                    purchaseOrder.Currency,
                    $"PO #{purchaseOrder.PoNumber} — Principal #{purchaseOrder.PrincipalId}",
                    new JournalEntryLineInput[]
                    {
                        new JournalEntryLineInput { Account = inventoryAccount, Debit = totalAmount, Credit = null, CostCenterId = purchaseOrder.TenderId },
                        new JournalEntryLineInput { Account = apAccount, Debit = null, Credit = totalAmount, CostCenterId = purchaseOrder.TenderId }
                    },
                    cancellationToken);

                purchaseOrder.JournalEntryId = entry.Id;
                _unitOfWork.Repository<PurchaseOrder, int>().Update(purchaseOrder);
                await _unitOfWork.SaveChangesAsync(cancellationToken);

                await transaction.CommitAsync(cancellationToken);
            }
            catch
            {
                await transaction.RollbackAsync(cancellationToken);
                throw;
            }
        }

        // ─── Shipment Costs ────────────────────────────────────────────────────
        // Debit:  Shipping Expense (5102) — Shipping + Customs
        // Credit: Cash/Bank (1101) — Amount paid
        public async Task PostShipmentAsync(Shipment shipment, CancellationToken cancellationToken = default)
        {
            var transaction = await _unitOfWork.BeginTransactionAsync(cancellationToken);
            try
            {
                var expenseAccount = await GetAccountByCodeAsync(AccountCodeShippingExpense, cancellationToken);
                var cashAccount = await GetAccountByCodeAsync(AccountCodeCash, cancellationToken);

                var totalCost = (shipment.ShippingCost ?? 0m) + (shipment.CustomsCost ?? 0m);
                if (totalCost <= 0) return; // No cost to post

                var entry = await CreateJournalEntryAsync(
                    "Shipment", shipment.Id,
                    CurrencyType.EGP, // Local costs
                    $"Shipment #{shipment.Id} — PO #{shipment.PurchaseOrderId} — Shipping & Customs",
                    new JournalEntryLineInput[]
                    {
                        new JournalEntryLineInput { Account = expenseAccount, Debit = totalCost, Credit = null, CostCenterId = shipment.PurchaseOrder.TenderId },
                        new JournalEntryLineInput { Account = cashAccount, Debit = null, Credit = totalCost, CostCenterId = shipment.PurchaseOrder.TenderId }
                    },
                    cancellationToken);

                shipment.JournalEntryId = entry.Id;
                _unitOfWork.Repository<Shipment, int>().Update(shipment);
                await _unitOfWork.SaveChangesAsync(cancellationToken);

                await transaction.CommitAsync(cancellationToken);
            }
            catch
            {
                await transaction.RollbackAsync(cancellationToken);
                throw;
            }
        }

        // ─── FabricationOrder Costs ────────────────────────────────────────────
        // Debit:  WIP (1302) — Fabrication cost
        // Credit: Accounts Payable (2101) — Amount owed to fabricator
        public async Task PostFabricationOrderAsync(FabricationOrder fabricationOrder, CancellationToken cancellationToken = default)
        {
            var transaction = await _unitOfWork.BeginTransactionAsync(cancellationToken);
            try
            {
                var wipAccount = await GetAccountByCodeAsync(AccountCodeWIP, cancellationToken);
                var apAccount = await GetAccountByCodeAsync(AccountCodeAccountsPayable, cancellationToken);

                var cost = fabricationOrder.FabricationCost ?? 0m;
                if (cost <= 0) return;

                var entry = await CreateJournalEntryAsync(
                    "FabricationOrder", fabricationOrder.Id,
                    CurrencyType.EGP,
                    $"Fabrication #{fabricationOrder.Id} — PO #{fabricationOrder.PurchaseOrderId}",
                    new JournalEntryLineInput[]
                    {
                        new JournalEntryLineInput { Account = wipAccount, Debit = cost, Credit = null, CostCenterId = null },
                        new JournalEntryLineInput { Account = apAccount, Debit = null, Credit = cost, CostCenterId = null }
                    },
                    cancellationToken);

                fabricationOrder.JournalEntryId = entry.Id;
                _unitOfWork.Repository<FabricationOrder, int>().Update(fabricationOrder);
                await _unitOfWork.SaveChangesAsync(cancellationToken);

                await transaction.CommitAsync(cancellationToken);
            }
            catch
            {
                await transaction.RollbackAsync(cancellationToken);
                throw;
            }
        }

        // ─── LetterOfCredit Opening ────────────────────────────────────────────
        // Debit:  LC Margin Deposit (1102) — Amount blocked
        // Credit: Cash/Bank (1101) — Amount withdrawn from bank
        public async Task PostLetterOfCreditAsync(LetterOfCredit letterOfCredit, CancellationToken cancellationToken = default)
        {
            var transaction = await _unitOfWork.BeginTransactionAsync(cancellationToken);
            try
            {
                var lcAccount = await GetAccountByCodeAsync(AccountCodeLCMargin, cancellationToken);
                var cashAccount = await GetAccountByCodeAsync(AccountCodeCash, cancellationToken);

                var entry = await CreateJournalEntryAsync(
                    "LetterOfCredit", letterOfCredit.Id,
                    letterOfCredit.Currency,
                    $"LC #{letterOfCredit.LcNumber} — {letterOfCredit.IssuingBank}",
                    new JournalEntryLineInput[]
                    {
                        new JournalEntryLineInput { Account = lcAccount, Debit = letterOfCredit.Amount, Credit = null, CostCenterId = null },
                        new JournalEntryLineInput { Account = cashAccount, Debit = null, Credit = letterOfCredit.Amount, CostCenterId = null }
                    },
                    cancellationToken);

                letterOfCredit.JournalEntryId = entry.Id;
                _unitOfWork.Repository<LetterOfCredit, int>().Update(letterOfCredit);
                await _unitOfWork.SaveChangesAsync(cancellationToken);

                await transaction.CommitAsync(cancellationToken);
            }
            catch
            {
                await transaction.RollbackAsync(cancellationToken);
                throw;
            }
        }

        // ─── Commission Received ───────────────────────────────────────────────
        // Debit:  Cash/Bank (1101) — Amount received
        // Credit: Commission Revenue (4201) — Commission income
        public async Task PostCommissionAsync(Commission commission, CancellationToken cancellationToken = default)
        {
            var transaction = await _unitOfWork.BeginTransactionAsync(cancellationToken);
            try
            {
                var cashAccount = await GetAccountByCodeAsync(AccountCodeCash, cancellationToken);
                var commissionRevenueAccount = await GetAccountByCodeAsync(AccountCodeCommissionRevenue, cancellationToken);

                var entry = await CreateJournalEntryAsync(
                    "Commission", commission.Id,
                    commission.Currency,
                    $"Commission #{commission.Id} — Principal #{commission.PrincipalId} — PO #{commission.PurchaseOrderId}",
                    new JournalEntryLineInput[]
                    {
                        new JournalEntryLineInput { Account = cashAccount, Debit = commission.Amount, Credit = null, CostCenterId = null },
                        new JournalEntryLineInput { Account = commissionRevenueAccount, Debit = null, Credit = commission.Amount, CostCenterId = null }
                    },
                    cancellationToken);

                commission.JournalEntryId = entry.Id;
                commission.Status = CommissionStatus.Received;
                commission.ReceivedAt = DateTime.UtcNow;
                _unitOfWork.Repository<Commission, int>().Update(commission);
                await _unitOfWork.SaveChangesAsync(cancellationToken);

                await transaction.CommitAsync(cancellationToken);
            }
            catch
            {
                await transaction.RollbackAsync(cancellationToken);
                throw;
            }
        }
    }
}