using System;
using System.Collections.Generic;
using System.Linq;
using Domain.Common;
using Domain.Enums;

namespace Domain.Models
{
    // =========================================================
    // 📒 القيد المحاسبي — كل معاملة مالية في النظام (فاتورة، دفعة،
    // راتب، أمر شراء، شحنة...) لازم تولّد قيد هنا تلقائيًا
    // =========================================================
    public class JournalEntry : BaseEntity<int>
    {
        public string ReferenceNumber { get; set; }
        public DateTime EntryDate { get; set; } = DateTime.UtcNow;
        public string? Description { get; set; }

        // عملة القيد وقت حدوثه (USD, EUR, EGP)
        public CurrencyType Currency { get; set; } = CurrencyType.EGP;

        // 🔗 مصدر القيد (Polymorphic): "Invoice", "Payment", "Salary", "PurchaseOrder", "Shipment"...
        public string SourceType { get; set; }
        public int SourceId { get; set; }

        public bool IsAutoGenerated { get; set; } = true;

        public ICollection<JournalEntryLine> Lines { get; set; } = new List<JournalEntryLine>();

        // ✅ لازم يكون صفر دايمًا في القيد المزدوج (بالعملة الأساسية للشركة)
        public decimal TotalDebitBase => Lines.Sum(l => l.DebitBaseCurrency);
        public decimal TotalCreditBase => Lines.Sum(l => l.CreditBaseCurrency);
        public bool IsBalanced => TotalDebitBase == TotalCreditBase;
    }

    public class JournalEntryLine : BaseEntity<int>
    {
        public int JournalEntryId { get; set; }
        public JournalEntry JournalEntry { get; set; }

        public int AccountId { get; set; }
        public Account Account { get; set; }

        // مركز التكلفة (المشروع/المناقصة) — لحساب ربحية كل مشروع فعليًا من واقع القيود
        public int? CostCenterId { get; set; }
        public CostCenter? CostCenter { get; set; }

        // 💱 القيمة بعملة المعاملة الأصلية
        public decimal Debit { get; set; }
        public decimal Credit { get; set; }

        // 🌍 القيمة محوّلة للعملة الأساسية للشركة وقت القيد (محاسبة دولية سليمة)
        public decimal ExchangeRateToBase { get; set; } = 1;
        public decimal DebitBaseCurrency { get; set; }
        public decimal CreditBaseCurrency { get; set; }
    }
}
