<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<ProjectReference Include="..\..\Core\ServiceAbstraction\ServiceAbstraction.csproj" />
		<ProjectReference Include="..\..\Core\Service\Service.csproj" />
	</ItemGroup>

</Project>
