using System;
using System.Collections.Generic;
using Domain.Enums;

namespace Shared.Dto.JournalEntries
{
    public class JournalEntryCreateDto
    {
        public string ReferenceNumber { get; set; } = null!;
        public DateTime EntryDate { get; set; }
        public string? Description { get; set; }
        public CurrencyType Currency { get; set; }
        public string SourceType { get; set; } = null!;
        public int SourceId { get; set; }
        public bool IsAutoGenerated { get; set; }
    }

    public class JournalEntryUpdateDto
    {
        public string ReferenceNumber { get; set; } = null!;
        public DateTime EntryDate { get; set; }
        public string? Description { get; set; }
        public CurrencyType Currency { get; set; }
        public string SourceType { get; set; } = null!;
        public int SourceId { get; set; }
        public bool IsAutoGenerated { get; set; }
    }

    public class JournalEntryResponseDto
    {
        public int Id { get; set; }
        public string ReferenceNumber { get; set; } = null!;
        public DateTime EntryDate { get; set; }
        public string? Description { get; set; }
        public CurrencyType Currency { get; set; }
        public string SourceType { get; set; } = null!;
        public int SourceId { get; set; }
        public bool IsAutoGenerated { get; set; }
    }

    public class JournalEntryDetailsDto : JournalEntryResponseDto
    {
        public List<JournalEntryLineResponseDto> Lines { get; set; } = new();
    }
}
